### ISSUE TITLE
Toxic Comments Plugin not working

### ISSUE THREAD

**Issue by lriggle-strib** [MinneapolisStarTribune/coral-project-talk#3]
## Description
The toxic comments plugin has been installed and the API key added to the feature environments, but the plugin generates errors when a comment is posted:

```text
talk_1  | Trace: TypeError: Cannot read property 'TOXICITY' of undefined
talk_1  |     at getScores (/usr/src/app/plugins/talk-plugin-toxic-comments/server/perspective.js:42:42)
talk_1  |     at <anonymous>
talk_1  |     at process._tickCallback (internal/process/next_tick.js:188:7)
talk_1  |     at getScore (/usr/src/app/plugins/talk-plugin-toxic-comments/server/hooks.js:23:13)
talk_1  |     at <anonymous>
talk_1  |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

The cause is unknown at this time.

cc: @marykenefick

**Comment by lriggle-strib** [comment]
The API key for the Perspective API (which is used to evaluate the toxicity of a comment) that was given to Ops for https://github.com/MinneapolisStarTribune/ansible-infrastructure/issues/2773 had a typo in it, so the application is unable to evaluate comment toxicity.

**Comment by lriggle-strib** [comment]
@marykenefick This issue was fixed in this PR: https://github.com/MinneapolisStarTribune/ansible-infrastructure/pull/2834
